### ISSUE TITLE
Does easing functions... ?

### ISSUE THREAD

**Issue by Kerollmops** [orhanbalci/rust-easing#2]
...always return the last input value if completing entire input array ?

``` rust
// Back::ease_in(X, 0f32, 10f32, 10f32)
Before [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
After [0, -0.0016745641, -0.006590193, -0.014584795, -0.025496267, -0.039162528,
       -0.05542147, -0.074111, -0.09506902, -0.11813346, -0.14314221]
```

http://easings.net/
In this example is it normal that the easing function doesn't reach the last value ?

**Comment by orhanbalci** [comment]
Hi @Kerosene2000  
Here are the parameters of an easing function

@t -- first parameters -- is the current time (or position) of the tween. This can be seconds or frames, steps, seconds, ms, whatever – as long as the unit is the same as is used for the total time [3].
@b-- second parameter -- is the beginning value of the property.
@c-- third parameters-- is the change between the beginning and destination value of the property.
@d-- fourth parameter-- is the total time of the tween.

Therefore for a full cycle tween your range should match the fourth parameter. In your example your fourth parameter is `10` but your first parameter range is `[0..1]`. This means you are animating first second of a 10 second animation. If you change your first parameter range to `[0..100]` easing function will reach its final destination. 

http://upshots.org/actionscript/jsas-understanding-easing

**Comment by Kerollmops** [comment]
Hum... OoooK !

Sorry, I fixed my code and understood what you said !

``` rust
// Back::ease_in(X, 0f32, 1f32, 1f32)
Before [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
After [0, -0.014314221, -0.046450563, -0.08019955, -0.09935168,
       -0.087697506, -0.02902751, 0.09286772, 0.29419786, 0.5911719, 1]
```

**Comment by orhanbalci** [comment]
You are welcome :)
